''' You can find this exercise at the following website: https://www.practicepython.org/

18. Cows and Bulls: 

Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number. '''

import random

def checking(userGuess, answer):
    cows = 0
    bulls = 0
    userGuess = list(userGuess)
    for i in range(4):
        if int(userGuess[i]) == int(answer[i]):
            cows += 1
        elif int(userGuess[i]) in answer and int(userGuess[i]) != int(answer[i]):
            bulls += 1
    print("Cows: " + str(cows) + "; Bulls: " + str(bulls))
    return cows
    
if __name__=="__main__":
    answer = []
    for i in range (4):
        answer.append(random.randint(0, 9))
    userGuess = ""
    playing = True
    counter = 0
    print("Welcome to the Cows and Bulls Game!")
    print()
    print("A cow is a correct digit in the correct place.")
    print("A bull is a correct digit in the wrong place.")
    print()
    while playing:
        userGuess = input("Guess a 4-digits number: ")
        if len(userGuess) != 4:
            print("Guess a 4-digits number!")
        else:
            counter += 1
            cows = checking(userGuess, answer)
            if cows == 4:
                print()
                print("Congratulations! Your guess is correct!")
                print("It took you " + str(counter) + " attempts.")
                playing = False